# Generated by Django 6.0.4 on 2026-04-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="numero_nota_fiscal",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                verbose_name="Número da Nota Fiscal",
            ),
        ),
    ]
