# Generated by Django 6.0.6 on 2026-06-04 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BemPermanente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('numero_patrimonio', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('localizacao', models.CharField(blank=True, max_length=150)),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('estado_conservacao', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('INSERVIVEL', 'Inservível')], default='BOM', max_length=10)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bem permanente',
                'verbose_name_plural': 'Bens permanentes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['categoria__name', 'nome'],
            },
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Estoque mínimo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='perecivel',
            field=models.BooleanField(default=False, verbose_name='Perecível'),
        ),
        migrations.AddField(
            model_name='produto',
            name='periodicidade',
            field=models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('EVENTUAL', 'Eventual')], default='EVENTUAL', max_length=8),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_legado', to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='core.categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.grupo'),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('categoria', 'nome'), name='unique_grupo_por_categoria'),
        ),
    ]
