# Generated by Django 6.0.6 on 2026-06-07 12:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_saldo_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FatorConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramas_por_aluno', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ativo', models.BooleanField(default=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fator_consumo', to='core.produto')),
            ],
            options={
                'verbose_name': 'Fator de consumo',
                'verbose_name_plural': 'Fatores de consumo',
            },
        ),
        migrations.CreateModel(
            name='FrequenciaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('INTEGRAL', 'Integral')], max_length=8)),
                ('turma', models.CharField(max_length=20)),
                ('quantidade_alunos', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frequencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Frequência diária',
                'verbose_name_plural': 'Frequências diárias',
                'ordering': ['-data', 'turno', 'turma'],
                'constraints': [models.UniqueConstraint(fields=('data', 'turno', 'turma'), name='unique_frequencia_por_turma_turno_dia')],
            },
        ),
    ]
