# Generated by Django 6.0.6 on 2026-07-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_turmas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
