# Generated by Django 6.0.6 on 2026-07-30 23:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_protect_pins_and_add_shared_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='data',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='produto',
            name='validade',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Validade'),
        ),
    ]
