# Generated by Django 6.0.6 on 2026-08-03 10:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_integral_turmas_and_refeicoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('refeicao', models.CharField(choices=[('CAFE_MANHA', 'Café da manhã'), ('ALMOCO', 'Almoço'), ('LANCHE_TARDE', 'Lanche da tarde')], max_length=12)),
                ('ativa', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['refeicao', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='frequenciadiaria',
            name='operacao_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='LoteEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80)),
                ('validade', models.DateField(blank=True, db_index=True, null=True)),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='core.entrada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='core.produto')),
            ],
            options={
                'verbose_name': 'Lote de estoque',
                'verbose_name_plural': 'Lotes de estoque',
                'ordering': [models.OrderBy(models.F('validade'), nulls_last=True), 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AlocacaoLoteMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes_lote', to='core.movimentacao')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='core.loteestoque')),
            ],
            options={
                'verbose_name': 'Alocação de lote',
                'verbose_name_plural': 'Alocações de lotes',
            },
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('refeicao', models.CharField(choices=[('CAFE_MANHA', 'Café da manhã'), ('ALMOCO', 'Almoço'), ('LANCHE_TARDE', 'Lanche da tarde')], max_length=12)),
                ('observacao', models.TextField(blank=True)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cardapios', to='core.receita')),
            ],
            options={
                'ordering': ['-data', 'refeicao'],
            },
        ),
        migrations.CreateModel(
            name='ReceitaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramas_por_aluno', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_em_receitas', to='core.produto')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='core.receita')),
            ],
            options={
                'ordering': ['produto__nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='loteestoque',
            constraint=models.UniqueConstraint(fields=('produto', 'codigo'), name='unique_lote_por_produto'),
        ),
        migrations.AddConstraint(
            model_name='loteestoque',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 0)), name='lote_quantidade_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='alocacaolotemovimentacao',
            constraint=models.UniqueConstraint(fields=('movimentacao', 'lote'), name='unique_alocacao_lote_movimentacao'),
        ),
        migrations.AddConstraint(
            model_name='cardapio',
            constraint=models.UniqueConstraint(fields=('data', 'refeicao'), name='unique_cardapio_por_refeicao_dia'),
        ),
        migrations.AddConstraint(
            model_name='receitaingrediente',
            constraint=models.UniqueConstraint(fields=('receita', 'produto'), name='unique_ingrediente_por_receita'),
        ),
    ]
