# Generated by Django 6.0.6 on 2026-08-18 22:31

import django.db.models.deletion
import plataforma.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cardapios_lotes_e_idempotencia'),
        ('plataforma', '0006_escola_municipio_tokenacesso_papel_rede_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardapioModeloMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('refeicao', models.CharField(choices=[('CAFE_MANHA', 'Café da manhã'), ('ALMOCO', 'Almoço'), ('LANCHE_TARDE', 'Lanche da tarde')], max_length=12)),
                ('ingredientes', models.JSONField(default=list)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cardápio modelo municipal',
                'verbose_name_plural': 'Cardápios modelo municipais',
                'ordering': ['refeicao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CatalogoProdutoMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=100)),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('L', 'Litro'), ('CX', 'Caixa'), ('PC', 'Pacote')], max_length=2)),
                ('estoque_minimo_sugerido', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('perecivel', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Item do catálogo municipal',
                'verbose_name_plural': 'Itens do catálogo municipal',
                'ordering': ['categoria', 'grupo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='RegistroRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('refeicao', models.CharField(choices=[('CAFE_MANHA', 'Café da manhã'), ('ALMOCO', 'Almoço'), ('LANCHE_TARDE', 'Lanche da tarde')], max_length=12)),
                ('porcoes_planejadas', models.PositiveIntegerField(default=0)),
                ('porcoes_produzidas', models.PositiveIntegerField(default=0)),
                ('porcoes_servidas', models.PositiveIntegerField(default=0)),
                ('sobra_limpa_kg', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('descarte_kg', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('custo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cardapio_atendido', models.BooleanField(default=True)),
                ('fonte', models.CharField(choices=[('AUTOMATICA', 'Automática'), ('MANUAL', 'Manual')], default='MANUAL', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de refeição',
                'verbose_name_plural': 'Registros de refeições',
                'ordering': ['-data', 'refeicao'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='cardapio',
            name='unique_cardapio_por_refeicao_dia',
        ),
        migrations.RemoveConstraint(
            model_name='frequenciadiaria',
            name='unique_frequencia_por_turma_turno_dia',
        ),
        migrations.RemoveConstraint(
            model_name='grupo',
            name='unique_grupo_por_categoria',
        ),
        migrations.RemoveConstraint(
            model_name='loteestoque',
            name='unique_lote_por_produto',
        ),
        migrations.RemoveConstraint(
            model_name='operacaobaixaproducao',
            name='unique_baixa_producao_por_refeicao_dia',
        ),
        migrations.AddField(
            model_name='bempermanente',
            name='escola',
            field=models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='bens_permanentes', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='escola',
            field=models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='cardapios', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='escola',
            field=models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='configuracaoalertas',
            name='escola',
            field=models.OneToOneField(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_alertas', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='escola',
            field=models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='escola',
            field=models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='frequenciadiaria',
            name='escola',
            field=models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='frequencias_diarias', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='escola',
            field=models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='loteestoque',
            name='escola',
            field=models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_estoque', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='escola',
            field=models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='operacaobaixaproducao',
            name='escola',
            field=models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='operacoes_baixa', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='pinacesso',
            name='escola',
            field=models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='pins_acesso', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='produto',
            name='escola',
            field=models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='receita',
            name='escola',
            field=models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='turma',
            name='escola',
            field=models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='plataforma.escola'),
        ),
        migrations.AlterField(
            model_name='bempermanente',
            name='numero_patrimonio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pinacesso',
            name='pin_fingerprint',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='bempermanente',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_patrimonio__isnull', False)), fields=('escola', 'numero_patrimonio'), name='unique_patrimonio_por_escola'),
        ),
        migrations.AddConstraint(
            model_name='cardapio',
            constraint=models.UniqueConstraint(fields=('escola', 'data', 'refeicao'), name='unique_cardapio_por_refeicao_dia'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('escola', 'name'), name='unique_categoria_por_escola'),
        ),
        migrations.AddConstraint(
            model_name='frequenciadiaria',
            constraint=models.UniqueConstraint(fields=('escola', 'data', 'turno', 'turma'), name='unique_frequencia_por_turma_turno_dia'),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('escola', 'categoria', 'nome'), name='unique_grupo_por_categoria'),
        ),
        migrations.AddConstraint(
            model_name='loteestoque',
            constraint=models.UniqueConstraint(fields=('escola', 'produto', 'codigo'), name='unique_lote_por_produto'),
        ),
        migrations.AddConstraint(
            model_name='operacaobaixaproducao',
            constraint=models.UniqueConstraint(fields=('escola', 'data', 'refeicao'), name='unique_baixa_producao_por_refeicao_dia'),
        ),
        migrations.AddConstraint(
            model_name='pinacesso',
            constraint=models.UniqueConstraint(fields=('escola', 'pin_fingerprint'), name='unique_pin_por_escola'),
        ),
        migrations.AddConstraint(
            model_name='receita',
            constraint=models.UniqueConstraint(fields=('escola', 'nome'), name='unique_receita_por_escola'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('escola', 'nome'), name='unique_turma_por_escola'),
        ),
        migrations.AddField(
            model_name='cardapiomodelomunicipal',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapios_modelo', to='plataforma.municipio'),
        ),
        migrations.AddField(
            model_name='catalogoprodutomunicipal',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_produtos', to='plataforma.municipio'),
        ),
        migrations.AddField(
            model_name='registrorefeicao',
            name='escola',
            field=models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='registros_refeicao', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='registrorefeicao',
            name='operacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_impacto', to='core.operacaobaixaproducao'),
        ),
        migrations.AddConstraint(
            model_name='cardapiomodelomunicipal',
            constraint=models.UniqueConstraint(fields=('municipio', 'nome'), name='unique_cardapio_modelo_municipio'),
        ),
        migrations.AddConstraint(
            model_name='catalogoprodutomunicipal',
            constraint=models.UniqueConstraint(fields=('municipio', 'nome', 'unidade'), name='unique_item_catalogo_municipal'),
        ),
        migrations.AddConstraint(
            model_name='registrorefeicao',
            constraint=models.UniqueConstraint(fields=('escola', 'data', 'refeicao'), name='unique_registro_refeicao_escola_dia'),
        ),
        migrations.AddConstraint(
            model_name='registrorefeicao',
            constraint=models.CheckConstraint(condition=models.Q(('sobra_limpa_kg__gte', 0)), name='sobra_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='registrorefeicao',
            constraint=models.CheckConstraint(condition=models.Q(('descarte_kg__gte', 0)), name='descarte_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='registrorefeicao',
            constraint=models.CheckConstraint(condition=models.Q(('custo_estimado__gte', 0)), name='custo_nao_negativo'),
        ),
    ]
