# Generated by Django 6.0.6 on 2026-08-18 23:21

import django.db.models.deletion
import django.utils.timezone
import plataforma.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_cardapiomodelomunicipal_catalogoprodutomunicipal_and_more'),
        ('plataforma', '0006_escola_municipio_tokenacesso_papel_rede_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContagemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('quantidade_sistema', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantidade_fisica', models.DecimalField(decimal_places=3, max_digits=10)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contagens_estoque_criadas', to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(default=plataforma.models.escola_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='contagens_estoque', to='plataforma.escola')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contagens_fisicas', to='core.produto')),
            ],
            options={
                'ordering': ['-data', 'produto__nome'],
                'constraints': [models.UniqueConstraint(fields=('escola', 'produto', 'data'), name='unique_contagem_produto_escola_dia'), models.CheckConstraint(condition=models.Q(('quantidade_fisica__gte', 0)), name='contagem_fisica_nao_negativa'), models.CheckConstraint(condition=models.Q(('quantidade_sistema__gte', 0)), name='contagem_sistema_nao_negativa')],
            },
        ),
    ]
