# Generated by Django 5.2 on 2026-08-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_unidades_de_consumo"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacao",
            name="corrige_movimentacao",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="estorno",
                to="core.movimentacao",
            ),
        ),
    ]
