# Generated by Django 6.0.8 on 2026-09-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_contagemestoque'),
        ('plataforma', '0007_escola_municipio_tokenacesso_papel_rede_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pinacesso',
            name='turma_obrigatoria_apenas_para_aluno_rep',
        ),
        migrations.AlterField(
            model_name='pinacesso',
            name='papel',
            field=models.CharField(choices=[('ALUNO_REP', 'Representante de turma'), ('COZINHA', 'Equipe da cozinha'), ('NUTRICIONISTA', 'Nutricionista')], default='ALUNO_REP', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='pinacesso',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('papel', 'ALUNO_REP'), ('turma__isnull', False)), models.Q(('papel__in', ['COZINHA', 'NUTRICIONISTA']), ('turma__isnull', True)), _connector='OR'), name='turma_obrigatoria_apenas_para_aluno_rep'),
        ),
    ]
