# Generated by Django 6.0.8 on 2026-09-06 13:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0027_contagemestoque'),
        ('plataforma', '0007_escola_municipio_tokenacesso_papel_rede_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('serie', models.CharField(max_length=40)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Não informado')], max_length=1)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.escola')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.turma')),
            ],
            options={
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('ABSORVENTE', 'Absorventes'), ('KIT_ESCOLAR', 'Kit escolar'), ('FARDAMENTO', 'Fardamento')], max_length=20)),
                ('estado', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('LIBERADA', 'Liberada'), ('SUSPENSA', 'Suspensa'), ('ENCERRADA', 'Encerrada')], default='RASCUNHO', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('liberado_em', models.DateTimeField(null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.escola')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemRodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='distribuicao.rodada')),
            ],
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('turma_nome', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=40)),
                ('entregue_em', models.DateTimeField(null=True)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distribuicao.aluno')),
                ('movimentos', models.ManyToManyField(to='core.movimentacao')),
                ('pin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pinacesso')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.turma')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinatarios', to='distribuicao.rodada')),
            ],
            options={
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['escola', 'ativo', 'turma'], name='distribuica_escola__fa12d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemrodada',
            constraint=models.UniqueConstraint(fields=('rodada', 'produto'), name='produto_unico_rodada'),
        ),
        migrations.AddConstraint(
            model_name='itemrodada',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='quantidade_entrega_positiva'),
        ),
        migrations.AddConstraint(
            model_name='destinatario',
            constraint=models.UniqueConstraint(fields=('rodada', 'aluno'), name='aluno_unico_rodada'),
        ),
    ]
