# Generated by Django 6.0.6 on 2026-08-18 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def criar_escopo_do_piloto(apps, schema_editor):
    """Coloca a instalação anterior em uma escola sem alterar os dados do piloto."""

    Municipio = apps.get_model("plataforma", "Municipio")
    Escola = apps.get_model("plataforma", "Escola")
    VinculoUsuario = apps.get_model("plataforma", "VinculoUsuario")
    Perfil = apps.get_model("plataforma", "Perfil")
    TokenAcesso = apps.get_model("plataforma", "TokenAcesso")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    municipio, _ = Municipio.objects.get_or_create(
        slug="municipio-piloto",
        defaults={"nome": "Município Piloto", "uf": "CE"},
    )
    escola, _ = Escola.objects.get_or_create(
        municipio=municipio,
        slug="escola-piloto",
        defaults={"nome": "Escola Piloto"},
    )

    papeis = dict(Perfil.objects.values_list("user_id", "papel"))
    for usuario in User.objects.iterator():
        gestor_rede = papeis.get(usuario.pk) == "ADMIN"
        papel = "GESTOR_REDE" if gestor_rede else "OPERADOR"
        VinculoUsuario.objects.get_or_create(
            user_id=usuario.pk,
            municipio=municipio,
            escola=None if gestor_rede else escola,
            papel=papel,
            defaults={"ativo": True},
        )
        TokenAcesso.objects.filter(user_id=usuario.pk, municipio__isnull=True).update(
            municipio=municipio,
            escola=escola,
            papel_rede=papel,
        )


def reverso_sem_destruir_dados(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_perfil_acesso_legado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('slug', models.SlugField()),
                ('codigo_inep', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['municipio__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('uf', models.CharField(default='CE', max_length=2)),
                ('slug', models.SlugField(unique=True)),
                ('codigo_ibge', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='tokenacesso',
            name='papel_rede',
            field=models.CharField(blank=True, choices=[('GESTOR_REDE', 'Gestor da rede'), ('GESTOR_ESCOLA', 'Gestor escolar'), ('NUTRICIONISTA', 'Nutricionista'), ('OPERADOR', 'Operador')], max_length=16),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='tokenacesso',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens_acesso', to='plataforma.escola'),
        ),
        migrations.AddField(
            model_name='escola',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escolas', to='plataforma.municipio'),
        ),
        migrations.AddField(
            model_name='tokenacesso',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens_acesso', to='plataforma.municipio'),
        ),
        migrations.CreateModel(
            name='VinculoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('GESTOR_REDE', 'Gestor da rede'), ('GESTOR_ESCOLA', 'Gestor escolar'), ('NUTRICIONISTA', 'Nutricionista'), ('OPERADOR', 'Operador')], max_length=16)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_usuarios', to='plataforma.escola')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_usuarios', to='plataforma.municipio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_rede', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo de usuário',
                'verbose_name_plural': 'Vínculos de usuários',
                'ordering': ['user__username', 'municipio__nome', 'escola__nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='escola',
            constraint=models.UniqueConstraint(fields=('municipio', 'slug'), name='unique_escola_slug_municipio'),
        ),
        migrations.AddConstraint(
            model_name='vinculousuario',
            constraint=models.UniqueConstraint(condition=models.Q(('escola__isnull', False)), fields=('user', 'municipio', 'escola', 'papel'), name='unique_vinculo_usuario_escola_papel'),
        ),
        migrations.AddConstraint(
            model_name='vinculousuario',
            constraint=models.UniqueConstraint(condition=models.Q(('escola__isnull', True)), fields=('user', 'municipio', 'papel'), name='unique_vinculo_usuario_rede_papel'),
        ),
        migrations.RunPython(criar_escopo_do_piloto, reverso_sem_destruir_dados),
    ]
