"""
Django settings for easystock project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

APP_ENV = os.environ.get("APP_ENV", "development").strip().lower()
IS_PRODUCTION = APP_ENV == "production"

# Produção deve falhar cedo se a chave não estiver configurada. A chave abaixo
# existe apenas para desenvolvimento/testes locais e nunca deve ser usada em deploy.
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    if IS_PRODUCTION:
        raise ImproperlyConfigured("SECRET_KEY é obrigatória quando APP_ENV=production.")
    SECRET_KEY = "django-insecure-edustock-development-only"

# Seguro por padrão: desenvolvimento com debug precisa ser habilitado explicitamente.
DEBUG = os.environ.get("DEBUG", "False").strip().lower() in ("1", "true", "yes")

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # APIs / frontend React
    "rest_framework",
    "corsheaders",
    "core",
    "plataforma",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # CORS precisa vir o mais alto possível (antes do CommonMiddleware)
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "easystock.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "easystock.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use PostgreSQL in production (Render), SQLite in development
if 'DATABASE_URL' in os.environ:
    DATABASES = {
        "default": dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Recife"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

if IS_PRODUCTION:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "3600"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = (
        os.environ.get("SECURE_HSTS_PRELOAD", "False").strip().lower()
        in ("1", "true", "yes")
    )
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"


# ------------------------------------------------------------------
# API REST + Frontend React (EasyStock)
# ------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "plataforma.pagination.EduStockPagination",
    "NUM_PROXIES": int(
        os.environ.get("TRUSTED_PROXY_COUNT", "1" if IS_PRODUCTION else "0")
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "plataforma.authentication.TokenAcessoAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# Origem do dev server do Vite (React) e produção
# Em produção, adicione os domínios da Render
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # frontend admin (dev)
    "http://127.0.0.1:5173",
    "http://localhost:5174",  # app-alunos (dev)
    "http://127.0.0.1:5174",
    "http://localhost:5175",  # app-cozinha (dev)
    "http://127.0.0.1:5175",
]

# Em produção, adicione dinamicamente os domínios do Render
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    CORS_ALLOWED_ORIGINS.extend([
        f'https://{RENDER_EXTERNAL_HOSTNAME}',
        'https://edustock-frontend.onrender.com',
        'https://edustock-alunos.onrender.com',
        'https://edustock-cozinha.onrender.com',
    ])
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CORS_ALLOW_CREDENTIALS = True

# Origens confiáveis para o Origin-check de CSRF do Django (Django 4+).
# Sem isso, qualquer POST vindo dos apps React via proxy do Vite (ex.:
# login por PIN em /api/operacao/auth/) recebe 403 "CSRF Failed: Origin
# checking failed", mesmo com CORS liberado — CORS e CSRF são checagens
# independentes. Mesma lista de origens que CORS_ALLOWED_ORIGINS.
CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)

# ------------------------------------------------------------------
# Módulo de Operação da Merenda
# ------------------------------------------------------------------
# PINs de turma/cozinha agora ficam em Turma/PinAcesso (banco), geridos
# pelo Django Admin — ver core/models.py e core/admin.py.

# Tempo de vida dos tokens de sessão em horas (padrão 12h)
OPERACAO_TOKEN_TTL_HORAS = 12

# ------------------------------------------------------------------
# Autenticação da plataforma (dashboard admin)
# ------------------------------------------------------------------
LOGIN_TOKEN_TTL_HORAS = int(os.environ.get('LOGIN_TOKEN_TTL_HORAS', 12))
LOGIN_MAX_TENTATIVAS = int(os.environ.get("LOGIN_MAX_TENTATIVAS", "5"))
LOGIN_JANELA_SEGUNDOS = int(os.environ.get("LOGIN_JANELA_SEGUNDOS", "300"))

# Sessões operacionais e rate limit precisam ser compartilhados entre workers.
# Redis é preferido; o cache de banco mantém o comportamento correto sem exigir
# um serviço adicional no primeiro deploy.
REDIS_URL = os.environ.get("REDIS_URL", "").strip()
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
            "KEY_PREFIX": "edustock",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": "edustock_cache",
            "KEY_PREFIX": "edustock",
            "TIMEOUT": 300,
        }
    }

PIN_LOGIN_MAX_TENTATIVAS = int(os.environ.get("PIN_LOGIN_MAX_TENTATIVAS", "5"))
PIN_LOGIN_JANELA_SEGUNDOS = int(os.environ.get("PIN_LOGIN_JANELA_SEGUNDOS", "300"))
PIN_LOOKUP_SECRET = os.environ.get("PIN_LOOKUP_SECRET", SECRET_KEY)
