"""
Django settings for easystock project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$ara9&n@l3x^ey=o$k51e6q5+je!p6304nk4ks@39ts4px_938"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # APIs / frontend React
    "rest_framework",
    "corsheaders",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # CORS precisa vir o mais alto possível (antes do CommonMiddleware)
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "easystock.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "easystock.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Recife"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


# ------------------------------------------------------------------
# API REST + Frontend React (EasyStock)
# ------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": None,
    # Em produção troque para IsAuthenticated e configure auth de sessão/token
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

# Origem do dev server do Vite (React)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # frontend admin
    "http://127.0.0.1:5173",
    "http://localhost:5174",  # app-alunos
    "http://127.0.0.1:5174",
    "http://localhost:5175",  # app-cozinha
    "http://127.0.0.1:5175",
]
CORS_ALLOW_CREDENTIALS = True

# ------------------------------------------------------------------
# Módulo de Operação da Merenda — PINs de acesso
# ------------------------------------------------------------------
# PIN de cada turma: { pin (str), turma, turno }
# Em produção, carregue de variável de ambiente ou arquivo seguro.
OPERACAO_PINS_ALUNOS = [
    {"pin": "1001", "turma": "6A", "turno": "MANHA"},
    {"pin": "1002", "turma": "6B", "turno": "MANHA"},
    {"pin": "1003", "turma": "7A", "turno": "MANHA"},
    {"pin": "1004", "turma": "7B", "turno": "TARDE"},
    {"pin": "1005", "turma": "8A", "turno": "TARDE"},
    {"pin": "1006", "turma": "8B", "turno": "TARDE"},
    {"pin": "1007", "turma": "9A", "turno": "INTEGRAL"},
]

# PIN único da cozinha
OPERACAO_PIN_COZINHA = "9999"

# Tempo de vida dos tokens de sessão em horas (padrão 12h)
OPERACAO_TOKEN_TTL_HORAS = 12
