"""
Django settings for easystock project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', "django-insecure-$ara9&n@l3x^ey=o$k51e6q5+je!p6304nk4ks@39ts4px_938")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # APIs / frontend React
    "rest_framework",
    "corsheaders",
    "core",
    "plataforma",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # CORS precisa vir o mais alto possível (antes do CommonMiddleware)
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "easystock.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "easystock.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use PostgreSQL in production (Render), SQLite in development
if 'DATABASE_URL' in os.environ:
    DATABASES = {
        "default": dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Recife"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ------------------------------------------------------------------
# API REST + Frontend React (EasyStock)
# ------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": None,
    # Em produção troque para IsAuthenticated e configure auth de sessão/token
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

# Origem do dev server do Vite (React) e produção
# Em produção, adicione os domínios da Render
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # frontend admin (dev)
    "http://127.0.0.1:5173",
    "http://localhost:5174",  # app-alunos (dev)
    "http://127.0.0.1:5174",
    "http://localhost:5175",  # app-cozinha (dev)
    "http://127.0.0.1:5175",
]

# Em produção, adicione dinamicamente os domínios do Render
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    CORS_ALLOWED_ORIGINS.extend([
        f'https://{RENDER_EXTERNAL_HOSTNAME}',
        'https://edustock-frontend.onrender.com',
        'https://edustock-alunos.onrender.com',
        'https://edustock-cozinha.onrender.com',
    ])
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CORS_ALLOW_CREDENTIALS = True

# Origens confiáveis para o Origin-check de CSRF do Django (Django 4+).
# Sem isso, qualquer POST vindo dos apps React via proxy do Vite (ex.:
# login por PIN em /api/operacao/auth/) recebe 403 "CSRF Failed: Origin
# checking failed", mesmo com CORS liberado — CORS e CSRF são checagens
# independentes. Mesma lista de origens que CORS_ALLOWED_ORIGINS.
CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)

# ------------------------------------------------------------------
# Módulo de Operação da Merenda
# ------------------------------------------------------------------
# PINs de turma/cozinha agora ficam em Turma/PinAcesso (banco), geridos
# pelo Django Admin — ver core/models.py e core/admin.py.

# Tempo de vida dos tokens de sessão em horas (padrão 12h)
OPERACAO_TOKEN_TTL_HORAS = 12
